version: '3.7'

services:

########################### NETWORKS
networks:
  proxy:
    external:
      name: proxy

# Plex

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
#      - UMASK_SET=022 #optional
      - PLEX_CLAIM=$PLEX_CLAIM_TOKEN
      - ADVERTISE_IP=https://plex.$DOMAINNAME:32400/
    volumes:
      - $PLEX_DATA/config:/config
      - $PLEX_MOVIES:/movies
      - $PLEX_TV:/tv-shows
      - $PLEX_PHOTOS:/photos
      - $PLEX_MUSIC:/music
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME`)"
      - "traefik.http.routers.plex-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.backups-rtr.middlewares=chain-authelia@file,add-backups" 
#      - "traefik.http.middlewares.add-backups.addPrefix.prefix=/backups"
      ## HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex-rtr.middlewares=chain-oauth@file"
