version: '3.7'

services:

########################### NETWORKS
networks:
  proxy:
    external:
      name: proxy

# Netdata

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: metrics.$DOMAINNAME # set to fqdn of host
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.metrics-rtr.entrypoints=https"
      - "traefik.http.routers.metrics-rtr.rule=Host(`metrics.$DOMAINNAME`)" 
      - "traefik.http.routers.metrics-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.metrics-rtr.middlewares=chain-oauth@file" 
      ## HTTP Services
      - "traefik.http.routers.metrics-rtr.service=metrics-svc"
      - "traefik.http.services.metrics-svc.loadbalancer.server.port=19999"
      - "traefik.http.routers.metrics-rtr.middlewares=chain-oauth@file"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
