version: '3.7'

services:

########################### NETWORKS
networks:
  proxy:
    external:
      name: proxy

# Watchtower

  watchtower:
    container_name: watchtower
    image:  containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
