version: '3.7'

networks:
  proxy:
    external:
      name: proxy

services:

#Duplicati

  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - CLI_ARGS= #optional
    volumes:
      - $DUPLICATI_DATA/config:/config
      - $DUPLICATI_DATA/backups/:/backups
#    ports:
#      - 8200:8200
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.backups-rtr.entrypoints=https"
      - "traefik.http.routers.backups-rtr.rule=Host(`backups.$DOMAINNAME`)"
      - "traefik.http.routers.backups-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.backups-rtr.middlewares=chain-authelia@file,add-backups" 
#      - "traefik.http.middlewares.add-backups.addPrefix.prefix=/backups"
      ## HTTP Services
      - "traefik.http.routers.backups-rtr.service=backups-svc"
      - "traefik.http.services.backups-svc.loadbalancer.server.port=8200"
      - "traefik.http.routers.backups-rtr.middlewares=chain-oauth@file"
