version: '3.7'

services:

########################### NETWORKS
networks:
  proxy:
    external:
      name: proxy

# Qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - $QBIT_DATA/config:/config
      - $QBIT_DOWNLOADS:/downloads
      - $QBIT_BOOKS:/books
      - $QBIT_MOVIES:/movies
      - $QBIT_TV:/tv-shows
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8842:8080
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbit-rtr.entrypoints=https"
      - "traefik.http.routers.qbit-rtr.rule=Host(`qbit.$DOMAINNAME`)"
      - "traefik.http.routers.qbit-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.backups-rtr.middlewares=chain-authelia@file,add-backups" 
#      - "traefik.http.middlewares.add-backups.addPrefix.prefix=/backups"
      ## HTTP Services
      - "traefik.http.routers.qbit-rtr.service=qbit-svc"
      - "traefik.http.services.qbit-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbit-rtr.middlewares=chain-oauth@file"
